name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      shell: bash
      run: sh do.sh build_ci
    - name: Run tests
      shell: bash
      run: sh do.sh test_ci 
